version: "3.9"
networks:
  roboshop:
    driver: bridge
volumes:
# This is equivalent to docker volume create [volume-name]. these are named volumes
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mysql
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis
  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq
  mongodb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongodb

services:
  web:
    image: web:v2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    image: vdps/mongo:v2
    container_name: mongo
    volumes:
    - mongodb:/data/db
  catalogue:
    image: vdps/catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: vdps/user:v2
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: vdps/cart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: vdps/mysql:v2
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: vdps/shipping:v2
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: vdps/payment:v2
    container_name: payment
    depends_on:
    - rabbitmq


